language: generic 
sudo: required

services:
    - docker

before_install:
    - docker build -t psantori/dockerized-react-app -f Dockerfile.dev .

script:
    - docker run -e CI=true psantori/dockerized-react-app npm run test

deploy:
    provider: elasticbeanstalk
    region:  "us-east-2"
    app: "dockerized-react-app"
    env: "DockerizedReactApp-env"
    bucket_name: "elasticbeanstalk-us-east-2-483538501796"
    bucket_path: "dockerized-react-app"
    on:
        branch: master
    access_key_id: "$AWS_ACCESS_KEY"
    secret_access_key: "$AWS_SECRET_KEY"
