language: generic 
sudo: required

services:
    - docker

before_install:
    - docker build -t psantori/dockerized-react-app -f Dockerfile.dev .

script:
    - docker run -e CI=true USERNAME/dockerized-react-app npm run test